## Put comments here that give an overall description of what your
## functions do

## Write a short comment describing this function

## makeCacheMatrix function creates a matrix object that can cache its inverse.

makeCacheMatrix <- function(x = matrix()) {
    invm <- NULL
    setm <- function(y) {
        x <<-y
        invm <<- NULL
    }
    getm <- function() { x }
    setinv <- function(sMatrix) invm <<- sMatrix
    getinv <- function() { invm }
    list(setm= setm,getm =getm, setinv = setinv, getinv = getinv)
}


## Write a short comment describing this function
## CacheSolve function computes the inverse of the matrix
## generated by MakeCacheMatrix function. the CacheSolve function 
## retrieves the inverse from the cache if matrix was not changed
## and inverse has been calculated. 

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
    
    invm = x$getinv()
    
    if (!is.null(invm)){
        message("cached data..")
        return(invm)
    }
    
    data = x$getm()
    invm = solve(data, ...)
    
    x$setinv(invm)
    return(invm)
}

## function results
#matrix <- makeCacheMatrix(matrix(1:4,2,2))
#> matrix$getm()
#[,1] [,2]
#[1,]    1    3
#[2,]    2    4
#> matrix$getinv()
#NULL
#> cacheSolve(matrix)
#[,1] [,2]
#[1,]   -2  1.5
#[2,]    1 -0.5
#> cacheSolve(matrix)
#cached data..
#[,1] [,2]
#[1,]   -2  1.5
#[2,]    1 -0.5
#> matrix$getinv()
#[,1] [,2]
#[1,]   -2  1.5
#[2,]    1 -0.5



